title: elonnzhang
description: "BLOG"
url: "https://elonnzhang.github.io"
baseurl: ""
lang: "zh-CN"
timezone: "Asia/Shanghai"
author:
  name: "elonnzhang"
  email: "elonnzhang@gmail.com"
  url: "https://elonnzhang.github.io"

source: .
destination: ./_site
permalink: /:title
paginate: 10
paginate_path: /page/:num/

exclude:
  - DEVELOPMENT.md
  - DESIGN.md
  - Makefile
  - README.md
  - jekyll-docs
  - Gemfile
  - Gemfile.lock
  - vendor
  - .bundle
  - .obsidian

include:
  - Clippings

collections:
  code_space:
    output: true
    permalink: /code-space/:path/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "Clippings"
    values:
      layout: "post"
      space: "clippings"
  -
    scope:
      path: ""
      type: "code_space"
    values:
      layout: "code-space-doc"
      space: "code-space"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

feed:
  path: atom.xml

# Custom variables
owner: "elonnzhang"
